# Generated by Django 3.2.22 on 2023-10-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='inquiry',
            new_name='property',
        ),
    ]
