# Generated by Django 3.2.22 on 2023-10-12 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.DecimalField(decimal_places=2, max_digits=7)),
                ('location', models.CharField(max_length=100)),
                ('num_rooms', models.PositiveSmallIntegerField()),
                # ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], max_length=10)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('Loft', 'Loft'), ('Flat', 'Flat'), ('Apartment', 'Apartment'),
                                                            ('Farmhouse', 'Farmhouse'), ('Condos', 'Condos'), ('Townhouse', 'Townhouse'),
                                                            ('Chalet', 'Chalet'), ('Studio', 'Studio')], max_length=20)),
                # ('num_interests', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='../default_post_rgq6aq', upload_to='images/')),
                ('image_filter', models.CharField(choices=[('_1977', '1977'), ('brannan', 'Brannan'), ('earlybird', 'Earlybird'), ('hudson', 'Hudson'), ('inkwell', 'Inkwell'), ('lofi', 'Lo-Fi'), ('kelvin', 'Kelvin'), ('normal', 'Normal'), ('nashville', 'Nashville'), ('rise', 'Rise'), ('toaster', 'Toaster'), ('valencia', 'Valencia'), ('walden', 'Walden'), ('xpro2', 'X-pro II')], default='normal', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
