# Generated by Django 3.2.22 on 2023-10-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, default='../default_property_rgq6aq', upload_to='images/'),
        ),
    ]
