# Generated by Django 3.2.22 on 2023-10-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_filter',
            field=models.CharField(choices=[('_1977', '1977'), ('normal', 'Normal')], default='normal', max_length=32),
        ),
    ]
